# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='naziwsko',
            new_name='nazwisko',
        ),
    ]
