# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170530_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('kat_id', models.AutoField(primary_key=True, serialize=False)),
                ('kat_nazwa', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('poz', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('produkt_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=25)),
                ('opis', models.TextField(max_length=120)),
                ('obrazek', models.CharField(default='', max_length=25)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('stan', models.IntegerField(default=0)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Kategoria')),
            ],
        ),
        migrations.AddField(
            model_name='koszyk',
            name='produkt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Produkty'),
        ),
    ]
