# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170607_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
