# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170608_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabela',
        ),
    ]
